name: anigas-attire-dev

services:
  frontend:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    container_name: anigas-attire-frontend-dev
    ports:
      - "3000:3000"   # Next.js dev server
      - "9229:9229"   # Node.js debugger
      - "9230:9230"   # Next.js router debugger
    env_file:
      - ../../.env.dev
    environment:
      - NODE_ENV=development
    volumes:
      # Mount entire project for live code updates + source maps
      - ../../:/app
      # Preserve container-specific node_modules
      - /app/node_modules
      # Sync .next folder to inspect generated files locally
      - ../../.next:/app/.next
    restart: unless-stopped
    networks:
      - anigas-network-dev
    # Enable for easier debugging
    stdin_open: true
    tty: true

  backend:
    image: infominsolutions/cashya-shoppy:latest
    pull_policy: missing  # Use local image for faster dev startup
    container_name: anigas-attire-backend-dev
    ports:
      - "5025:5025"
    env_file:
      - ../../.env.dev
    environment:
      - DEBUG=True
    restart: unless-stopped
    networks:
      - anigas-network-dev

networks:
  anigas-network-dev:
    driver: bridge
