name: anigas-attire

services:
  frontend:
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    container_name: anigas-attire-frontend
    ports:
      - "3000:3000"
    env_file:
      - ../../.env
    restart: unless-stopped
    extra_hosts:
      - "localhost:host-gateway"
    networks:
      - anigas-network

  backend:
    image: infominsolutions/cashya-shoppy:latest
    pull_policy: always
    container_name: anigas-attire-backend
    ports:
      - "8000:8000"
    env_file:
      - ../../.env
    restart: unless-stopped
    networks:
      - anigas-network
    volumes:
      - backend-data:/app/data
      

networks:
  anigas-network:
    driver: bridge

volumes:
  backend-data:
    name: anigas-attire-backend-data
